### PR TITLE
Add Travis CI

### PR DESCRIPTION
**Pull request by yukiisbored**
Post merge notes:
- Register to travis-ci.org with GitHub
- Enable "flytrap" repo. (You may need to sync your account first)

You can see the build under my fork on Travis: https://travis-ci.org/yukiisbored/flytrap/builds/323067898

### CODE REVIEW

**Comment by OrdinaryMagician** [comment]
What would be the usefulness of this? I always check that things build before committing anything.

**Comment by yukiisbored** [comment]
One of which is to check the states of pull requests. But the real deal is you can make a changes onto another branch, do some work, some of them may break something, and you can just commit to that branch and push it, check the CI builds and see if it'll pass or not.

It makes development so much easier, so you can always ensure you future changes won't break the project.

And when you're done and think it's good, you can merge it to master.

**Comment by OrdinaryMagician** [comment]
Ehhhhh, it's probably going to sound awkward but I don't usually work with branches. Especially not on projects as small as this.

**Comment by yukiisbored** [comment]
Ah okay then, you can just reopen this PR if you want it.

**Pull request closed without merging**
